# Generated by Django 6.1 on 2026-08-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMarketCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('news_count_correlation', models.FloatField(blank=True, null=True)),
                ('sentiment_price_correlation', models.FloatField(blank=True, null=True)),
                ('sentiment_volume_correlation', models.FloatField(blank=True, null=True)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_correlations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vwap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pressure_label', models.CharField(blank=True, max_length=50)),
                ('pressure_score', models.FloatField(blank=True, null=True)),
                ('volume_ratio', models.FloatField(blank=True, null=True)),
                ('volume_zscore', models.FloatField(blank=True, null=True)),
                ('volume_anomaly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_analysis', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_company_behavior_date')],
            },
        ),
    ]
