# Generated by Django 6.1 on 2026-08-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=14)),
                ('high', models.DecimalField(decimal_places=2, max_digits=14)),
                ('low', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close', models.DecimalField(decimal_places=2, max_digits=14)),
                ('volume', models.BigIntegerField()),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='companies.company')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_company_price_date')],
            },
        ),
        migrations.CreateModel(
            name='FloorsheetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('transaction_no', models.CharField(blank=True, max_length=100)),
                ('buyer_broker', models.CharField(max_length=50)),
                ('seller_broker', models.CharField(max_length=50)),
                ('quantity', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorsheet_transactions', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'trade_date'], name='market_floo_company_497647_idx')],
            },
        ),
    ]
