# Generated by Django 6.1 on 2026-08-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='floorsheettransaction',
            constraint=models.UniqueConstraint(fields=('company', 'trade_date', 'transaction_no'), name='unique_floorsheet_transaction'),
        ),
    ]
