# Generated by Django 6.1 on 2026-08-24 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorizationCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.BooleanField()),
                ('new_value', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='news.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('method', models.CharField(default='rule_based', max_length=50)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tags', to='news.newsarticle')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_tags', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'company'), name='unique_article_company_tag')],
            },
        ),
    ]
